### PR TITLE
Add Java 8 Support

### PR DESCRIPTION
**Pull request by Glavo**
I can't test it on Java 8 at the moment, because `io.github.humbleui:types` is compiling with Java 9. I need to migrate it first, which takes a little time.

### CODE REVIEW

**Comment by Glavo** [comment]
https://github.com/HumbleUI/Types/pull/2

I ran the example `RenderToBitmap` on Java 8, and it works well.

image

But I think maybe it needs more tests to prove its correctness.

**Comment by tonsky** [comment]
Ha, testing is indeed tricky. All tests and examples are written in modern java :) Well, at least as long as Java 9+ is working, I’m happy

**Comment by tonsky** [comment]
Merged in 2a1b3bdb9de461d509535ddd924ac7dd1894499a, thanks! Will cut a release soon

**Comment by tonsky** [comment]
Pushed 0.109.0. Thanks for the contribution!

**Pull request closed without merging**
