### PR TITLE
fix #6: Upgrade LWJGL to 3.3.1

### LINKED ISSUE #6: Migrate Clojure examples to JWM
Copied from https://github.com/JetBrains/skija/issues/125

### PR DESCRIPTION
**Pull request by Glavo**
Upgrade LWJGL to allow run LWJGL examples on the Apple Silicon machine.

image

### CODE REVIEW

**Comment by tonsky** [comment]
Thanks!

**Comment by tonsky** [comment]
Do you get shader compilation errors on SVG Tiger and other scenes?
Screenshot 2022-12-29 at 13 23 39
Screenshot 2022-12-29 at 13 23 34

**Comment by Glavo** [comment]
@tonsky I tried to run the lwjgl example and got the same error.

Even if I use Rosetta 2 to run the example, this error still occurs.

I have no idea about this problem, so I can't find out the cause of the problem.

**Comment by tonsky** [comment]
Yeah, no worries, probably something in Skia sources or GL version. I just wanted to confirm that I’m not the only one

**Pull request merged**
